package io.seoj17.android_14th_compose_zzik.ui.model

import androidx.compose.runtime.Stable
import androidx.compose.ui.res.stringResource
import io.seoj17.android_14th_compose_zzik.R

@Stable
class UpBitCoin(
    val market: String,
    val koreanName: String,
    val englishName: String,
    val tradePrice: Float,
    val accTradePrice: Float,
    val signedChangePrice : Float,
    val signedChangeRate : Float,
)

val coinList = listOf(
    UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),
    UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),
    UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),
    UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),
    UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),
    UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),
    UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),
    UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),
    UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),
    UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),
    UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),
    UpBitCoin(
        market = "KRW",
        koreanName = "비트코인",
        englishName = "BTC/KRW",
        tradePrice = 945710.00f,
        accTradePrice = 692469f,
        signedChangePrice = -2365000f,
        signedChangeRate = -2.45f,
    ),
)
