package io.seoj17.android_14th_compose_zzik.ui.model

import androidx.compose.runtime.Stable

@Stable
class UpBitCoin(
    val market: String,
    val koreanName: String,
    val englishName: String,
    val tradePrice: Float,
    val accTradePrice: Float,
    val signedChangePrice: Float,
    val signedChangeRate: Float,
)

val coinList = listOf(
    listOf(
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "KRW",
            koreanName = "도지코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
    ),
    listOf(
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "BTC",
            koreanName = "비트코인",
            englishName = "BTC/KRW",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
    ),
    listOf(
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = 2365000f,
            signedChangeRate = 2.45f,
        ),
        UpBitCoin(
            market = "USDT",
            koreanName = "이더리움",
            englishName = "BTC/USDT",
            tradePrice = 945710.00f,
            accTradePrice = 692469f,
            signedChangePrice = -2365000f,
            signedChangeRate = -2.45f,
        ),
    )
)
